### ISSUE TITLE
Cannot import sparkpost

### ISSUE THREAD

**Issue by suchow** [SparkPost/python-sparkpost#139]
```bash
/sparkpost git/master
❯ pip list
appdirs (1.4.0)
packaging (16.8)
pip (9.0.1)
pyparsing (2.1.10)
requests (2.13.0)
setuptools (34.2.0)
six (1.10.0)
sparkpost (1.3.4)
wheel (0.29.0)

/sparkpost git/master
❯ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sparkpost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jordansuchow/.virtualenvs/sparkpost/lib/python2.7/site-packages/sparkpost/__init__.py", line 9, in <module>
    from .transmissions import Transmissions
  File "/Users/jordansuchow/.virtualenvs/sparkpost/lib/python2.7/site-packages/sparkpost/transmissions.py", line 4, in <module>
    from email.utils import parseaddr
  File "email.py", line 1, in <module>
    from sparkpost import SparkPost
ImportError: cannot import name SparkPost

>>> from sparkpost import SparkPost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jordansuchow/.virtualenvs/sparkpost/lib/python2.7/site-packages/sparkpost/__init__.py", line 9, in <module>
    from .transmissions import Transmissions
  File "/Users/jordansuchow/.virtualenvs/sparkpost/lib/python2.7/site-packages/sparkpost/transmissions.py", line 4, in <module>
    from email.utils import parseaddr
  File "email.py", line 1, in <module>
    from sparkpost import SparkPost
ImportError: cannot import name SparkPost
```

**Comment by suchow** [comment]
(This is in a fresh virtual environment on Python 2.7, Mac OS X 10.11.6.)

**Comment by richleland** [comment]
Hi @suchow I am unable to recreate this issue. Could you create a fresh virtualenv again named something other than sparkpost and paste the entire chain of commands from `mkvirtualenv` to executing the code? For reference, here's the same on my machine:

```bash
 rleland  ~  mkvirtualenv pysp-issue139
New python executable in /Users/rleland/.virtualenvs/pysp-issue139/bin/python2.7
Also creating executable in /Users/rleland/.virtualenvs/pysp-issue139/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/rleland/.virtualenvs/pysp-issue139/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/rleland/.virtualenvs/pysp-issue139/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/rleland/.virtualenvs/pysp-issue139/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/rleland/.virtualenvs/pysp-issue139/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/rleland/.virtualenvs/pysp-issue139/bin/get_env_details

(pysp-issue139)  rleland  ~  pip install sparkpost
Collecting sparkpost
  Downloading sparkpost-1.3.4-py2.py3-none-any.whl
Collecting requests>=2.5.1 (from sparkpost)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Installing collected packages: requests, sparkpost
Successfully installed requests-2.13.0 sparkpost-1.3.4

(pysp-issue139)  rleland  ~  python
Python 2.7.12 (default, Oct 11 2016, 05:24:00)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sparkpost import SparkPost
>>> sp = SparkPost()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rleland/.virtualenvs/pysp-issue139/lib/python2.7/site-packages/sparkpost/__init__.py", line 24, in __init__
    raise SparkPostException("No API key. Improve message.")
sparkpost.exceptions.SparkPostException: No API key. Improve message.
>>>

(pysp-issue139)  rleland  ~  pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.0)
packaging (16.8)
pip (9.0.1)
pyparsing (2.1.10)
requests (2.13.0)
setuptools (34.2.0)
six (1.10.0)
sparkpost (1.3.4)
wheel (0.30.0a0)
```

**Comment by suchow** [comment]
@richleland Thanks. I can't reproduce this either now, hurray.
