### ISSUE TITLE
Receiving frequent ECONNRESET errors

### ISSUE THREAD

**Issue by jdotjdot** [SparkPost/python-sparkpost#174]
We started receiving regular errors appearing to originate from the `python-sparkpost` library when trying to send transmissions.  They fail deep in a dependent library from what appears to be a connection reset, but it's hard to tell. We upgraded everything we could think of to the latest version (New Relic, `requests`, `sparkpost`, `pyopenssl`, `cryptography`) but this is continuing to happen and causing us to frequently drop emails.

We believe at this point this is due to something in the Sparkpost library. Do you have any idea what it might be?

Traceback below:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/newrelic/hooks/application_celery.py", line 85, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/TCJ/utils/transactional_emails/mpc_emails.py", line 111, in send_interval_email
    sparky.send_transmissions(**message)
  File "/code/TCJ/utils/sparkpost_wrapper.py", line 153, in send_transmissions
    result = self.sp.transmissions.send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/sparkpost/transmissions.py", line 255, in send
    results = self.request('POST', self.uri, data=data)
  File "/usr/local/lib/python3.6/site-packages/sparkpost/base.py", line 41, in request
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sparkpost/base.py", line 12, in request
    response = self.sess.request(method, uri, headers=headers, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/newrelic/api/external_trace.py", line 62, in dynamic_wrapper
    return return_value(trace, lambda: wrapped(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/newrelic/api/coroutine_trace.py", line 171, in return_value
    return fn()
  File "/usr/local/lib/python3.6/site-packages/newrelic/api/external_trace.py", line 62, in <lambda>
    return return_value(trace, lambda: wrapped(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/newrelic/hooks/external_urllib3.py", line 21, in _nr_wrapper_make_request_
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/newrelic/hooks/external_urllib3.py", line 21, in _nr_wrapper_make_request_
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/site-packages/newrelic/hooks/external_httplib.py", line 75, in httplib_getresponse_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 290, in recv_into
    raise SocketError(str(e))
ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/newrelic/hooks/external_urllib3.py", line 21, in _nr_wrapper_make_request_
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/newrelic/hooks/external_urllib3.py", line 21, in _nr_wrapper_make_request_
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/site-packages/newrelic/hooks/external_httplib.py", line 75, in httplib_getresponse_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 290, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 285, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1370, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (104, 'ECONNRESET')Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python3.6/site-packages/newrelic/hooks/external_httplib.py", line 75, in httplib_getresponse_wrapper
    return wrapped(*args, **kwargs)
TypeError: getresponse() got an unexpected keyword argument 'buffering'
```

**Comment by jgzamora** [comment]
Hey @jdotjdot sorry about this issue & thanks for reporting. I haven't run into an issue like this, is it still a problem? 
If so, first thing I'd try to make sure is that TLS 1.2 is supported throughout your system. Your recent updates probably made sure that was the case, but just to be sure please check using these instructions: http://pyfound.blogspot.com/2017/01/time-to-upgrade-your-python-tls-v12.html

**Comment by jdotjdot** [comment]
It turned out to be a NAT gateway issue, unrelated to Sparkpost.
